apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  labels:
    release: prometheus
  name: titanic
spec:
  endpoints:

  - path: /metrics
    port: titanic
    scheme: http
    interval: 30s

  jobLabel: titanic
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: titanic