apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  labels:
    release: prometheus
  name: contacts-in-item
spec:
  endpoints:

  - path: /metrics
    port: contacts-in-item
    scheme: http
    interval: 30s

  jobLabel: contacts-in-item
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: contacts-in-item